resources:
 - ../../base/prometheus-trigger

components:
 - ../../components/sailfish-gateway
 - ../../components/broker-scale-to-zero
 - ../../components/high-availability



images:
  - name: sailfish-manager
    newName: zeidaof/sailfish-runmanager
  - name: sailfish-worker
    newName: zeidaof/sailfish-worker
  - name: sailfish-gateway
    newName: zeidaof/sailfish-gateway

patches:
## JOBS ##

# MANAGER
## This job will listen to the Job Queue
- target:
    group: keda.sh
    version: v1alpha1
    kind: ScaledJob
    name: sailfish-manager-autoscaler
  path: manager-job.yaml

# RUNNER
## This job will listen to the Task Queue
- target:
    group: keda.sh
    version: v1alpha1
    kind: ScaledJob
    name: sailfish-worker-autoscaler
  path: worker-job.yaml