- op: replace
  path: "/spec/jobTargetRef/template/spec"
  value:
    # Provide your own container that you'd like to run as a Run Manager (splits Job into Tasks)
    containers:
    - name: run-manager
      image: sailfish-run-manager
      imagePullPolicy: Always
      env:
        - name: AMQ_USER
          valueFrom:
            secretKeyRef:
              name: sailfish-broker-credentials-secret
              key: AMQ_USER
        - name: AMQ_PASSWORD
          valueFrom:
            secretKeyRef:
              name: sailfish-broker-credentials-secret
              key: AMQ_PASSWORD
        - name: MY_POD_NAMESPACE
          valueFrom:
            fieldRef:
              fieldPath: metadata.namespace
        - name: HOST
          value: sailfish-broker-hdls-svc.$(MY_POD_NAMESPACE).svc.cluster.local
        - name: QUEUE_PORT
          value: '5672'
      resources:
        requests:
          memory: "4G"
          cpu: '1'
        limits:
          memory: "4G"
      terminationMessagePath: /dev/termination-log
      terminationMessagePolicy: File          
    restartPolicy: Never