kind: Component

resources:
  - amq-broker-autoscaler.yaml

replacements:
  - source:
      name: sailfish-amq-broker-autoscaler
      kind: ScaledObject
      group: keda.sh
      version: v1alpha1
      fieldPath: metadata.namespace
    targets:
      - select:
          kind: ScaledObject
          group: keda.sh
          version: v1alpha1
          name: sailfish-amq-broker-autoscaler
        fieldPaths:
          - spec.triggers.0.metadata.namespace
      - select:
          kind: ScaledObject
          group: keda.sh
          version: v1alpha1
          name: sailfish-amq-broker-autoscaler
        fieldPaths:
          - spec.triggers.1.metadata.namespace
      - select:
          kind: ScaledObject
          group: keda.sh
          version: v1alpha1
          name: sailfish-amq-broker-autoscaler
        fieldPaths:
          - spec.triggers.2.metadata.namespace