apiVersion: keda.sh/v1alpha1
kind: ScaledObject
metadata:
  name: amq-broker-scaledobject
spec:
  scaleTargetRef:
    apiVersion: broker.amq.io/v1beta1
    kind: ActiveMQArtemis
    name: sailfish-broker
  pollingInterval: 2
  cooldownPeriod: 10
  minReplicaCount: 0   
  maxReplicaCount: 1   
  triggers:
    # 
    - type: prometheus
      metadata:
        serverAddress: https://thanos-querier.openshift-monitoring.svc.cluster.local:9092
        query: sum(kube_pod_status_ready{condition="true",pod=~"sailfish-gateway.+"})
        threshold: '1'
        authModes: "bearer"
        namespace: sailfish-demo  # Replaced in overlay
      authenticationRef:
        name: sailfish-trigger-auth
    - type: prometheus
      metadata:
        serverAddress: https://thanos-querier.openshift-monitoring.svc.cluster.local:9092
        query: sum(kube_pod_status_phase{phase!="Succeeded",phase!="Failed",pod=~"sailfish-run-manager.+"})
        threshold: '1'
        authModes: "bearer"
        namespace: sailfish-demo  # Replaced in overlay
      authenticationRef:
        name: sailfish-trigger-auth
    - type: prometheus
      metadata:
        serverAddress: https://thanos-querier.openshift-monitoring.svc.cluster.local:9092
        query: sum(kube_pod_status_phase{phase!="Succeeded",phase!="Failed",pod=~"sailfish-runner.+"})
        threshold: '1'
        authModes: "bearer"
        namespace: sailfish-demo  # Replaced in overlay
      authenticationRef:
        name: sailfish-trigger-auth