apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: sync-job-role
rules:
- apiGroups: 
    - "keda.sh"
  resources: 
    - "scaledjobs"
    - "scaledobjects"
  verbs: 
    - "get"
    - "list"
    - "patch"
