apiVersion: autoscaling.openshift.io/v1beta1
kind: MachineAutoscaler
metadata:
  name: {{ .Values.clusterName }}-{{ .Values.application }}-sailfish-machineset-1-machineautoscaler
  namespace: openshift-machine-api
  finalizers:
    - machinetarget.autoscaling.openshift.io
spec:
  maxReplicas: {{ .Values.maxMachinesPerZone }}
  minReplicas: 0
  scaleTargetRef:
    apiVersion: machine.openshift.io/v1beta1
    kind: MachineSet
    name: {{ .Values.clusterName }}-{{ .Values.application }}-sailfish-machineset-1