apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: sailfish-prometheus-view
subjects:
- kind: ServiceAccount
  name: sailfish
roleRef:
  kind: Role
  name: thanos-metrics-reader
  apiGroup: rbac.authorization.k8s.io
