resources:
 - ../foundation
 - permissions
 - servicemonitor.yaml

replacements:
  - source:
      name: sailfish-run-manager-autoscaler
      kind: ScaledJob
      group: keda.sh
      version: v1alpha1
      fieldPath: metadata.namespace
    targets:
      - select:
          kind: ScaledJob
          group: keda.sh
          version: v1alpha1
          name: sailfish-run-manager-autoscaler
        fieldPaths:
          - spec.triggers.0.metadata.namespace
  - source:
      name: sailfish-runner-autoscaler
      kind: ScaledJob
      group: keda.sh
      version: v1alpha1
      fieldPath: metadata.namespace
    targets:
      - select:
          kind: ScaledJob
          group: keda.sh
          version: v1alpha1
          name: sailfish-run-manager-autoscaler
        fieldPaths:
          - spec.triggers.0.metadata.namespace

patches:
- target:
    group: keda.sh
    version: v1alpha1
    kind: ScaledJob
    name: sailfish-run-manager-autoscaler
  path: run-manager-trigger.yaml

- target:
    group: keda.sh
    version: v1alpha1
    kind: ScaledJob
    name: sailfish-runner-autoscaler
  path: runner-trigger.yaml