kind: Component

patches:
- target:
    group: broker.amq.io
    version: v1beta1
    kind: ActiveMQArtemis
    name: sailfish-broker
  patch: |-
    - op: remove
      path: /spec/deploymentPlan/storage
      
- target:
    group: broker.amq.io
    version: v1beta1
    kind: ActiveMQArtemis
    name: sailfish-broker
  patch: |-
    - op: replace
      path: /spec/deploymentPlan/persistenceEnabled
      value: false