apiVersion: machine.openshift.io/v1beta1
kind: MachineSet
metadata:
  annotations:
    autoscaling.openshift.io/machineautoscaler: openshift-machine-api/{{ .Values.clusterName }}-{{ .Values.application }}-sailfish-machineset-1-machineautoscaler
  name: {{ .Values.clusterName }}-{{ .Values.application }}-sailfish-machineset-1
  namespace: openshift-machine-api
  labels:
    machines: sailfish
spec:
  replicas: 0
  selector:
    matchLabels:
      machine.openshift.io/cluster-api-cluster: {{ .Values.clusterName }}
      machine.openshift.io/cluster-api-machineset: {{ .Values.clusterName }}-sailfish-machineset-1
      sailfish/application: {{ .Values.application }}
  template:
    metadata:
      labels:
        machine.openshift.io/cluster-api-cluster: {{ .Values.clusterName }}
        machine.openshift.io/cluster-api-machine-role: worker
        machine.openshift.io/cluster-api-machine-type: worker
        machine.openshift.io/cluster-api-machineset: {{ .Values.clusterName }}-sailfish-machineset-1
        sailfish/application: {{ .Values.application }}
    spec:
      lifecycleHooks: {}
      metadata:
        labels:
          sailfish/application: {{ .Values.application }}
      providerSpec:
        value:
          {{- if .Values.enableSpotVM }}
          spotVMOptions: {}
          {{- end }}
          osDisk:
            diskSettings: {}
            diskSizeGB: 128
            managedDisk:
              storageAccountType: Premium_LRS
            osType: Linux
          networkResourceGroup: {{ .Values.networkResourceGroup }}
          publicLoadBalancer: {{ .Values.clusterName }}
          userDataSecret:
            name: worker-user-data
          vnet: {{ .Values.clusterVnet }}
          credentialsSecret:
            name: azure-cloud-credentials
            namespace: openshift-machine-api
          zone: '1'
          tags:
            owner: {{ .Values.owner | default "owner-tag-not-set" }}
            application: {{ .Values.application }}
          metadata:
            creationTimestamp: null
          publicIP: false
          resourceGroup: {{ .Values.aroResourceGroup }}
          kind: AzureMachineProviderSpec
          location: westeurope
          vmSize: {{ .Values.vmSize }}
          image:
            offer: aro4
            publisher: azureopenshift
            resourceID: ''
            sku: aro_412
            version: 412.86.20230503
          subnet: {{ .Values.workerSubnet }}
          apiVersion: azureproviderconfig.openshift.io/v1beta1
      taints:
        - effect: NoSchedule
          key: application
          value: sailfish-hpc
