apiVersion: serving.knative.dev/v1
kind: Service
metadata:
  name: sailfish-gateway
spec:
  template:
    metadata:
      annotations:
        autoscaling.knative.dev/max-scale: "1"
    spec:
      containers:
        - name: api-gateway
          image: zeidaof/sailfish-gateway
          env:
          - name: AMQ_USER
            valueFrom:
              secretKeyRef:
                name: sailfish-broker-credentials-secret
                key: AMQ_USER
          - name: AMQ_PASSWORD
            valueFrom:
              secretKeyRef:
                name: sailfish-broker-credentials-secret
                key: AMQ_PASSWORD
          - name: MY_POD_NAMESPACE
            valueFrom:
              fieldRef:
                fieldPath: metadata.namespace
          - name: HOST
            value: sailfish-broker-hdls-svc.$(MY_POD_NAMESPACE).svc.cluster.local
          - name: QUEUE_PORT
            value: '5672'
          ports:
            - containerPort: 8080
              protocol: TCP
          resources:
            requests:
              memory: "250M"
              cpu: "300m"
            limits:
              memory: "1G"
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
          imagePullPolicy: Always
