apiVersion: keda.sh/v1alpha1
kind: KedaController
metadata:
  name: keda
  namespace: openshift-keda
  finalizers:
    - finalizer.kedacontroller.keda.k8s.io
spec:
  metricsServer:
    logLevel: '0'
  operator:
    logEncoder: console
    logLevel: info
  serviceAccount: {}
  watchNamespace: ''
