apiVersion: broker.amq.io/v1beta1
kind: ActiveMQArtemisAddress
metadata:
  name: sailfish-dispatch-address
spec:
  addressName: sailfishDispatch
  applyToCrNames:
    - sailfish-broker
  queueName: sailfishDispatch
  routingType: anycast
  queueConfiguration:
        routingType: anycast
        durable: true
        maxConsumers: -1
        exclusive: false