apiVersion: keda.sh/v1alpha1
kind: ScaledJob
metadata:
  name: sailfish-run-manager-autoscaler
  labels:
    app: sailfish-run-manager
    app.kubernetes.io/component: sailfish-run-manager
    app.kubernetes.io/instance: sailfish-run-manager
    app.kubernetes.io/name: sailfish-run-manager
    app.kubernetes.io/part-of: sailfish-app
    app.openshift.io/runtime: python
spec:
  jobTargetRef:
    ttlSecondsAfterFinished: 100000 # completed or failed jobs will be removed after 100 seconds note that it successful an failed JobsHistoryLimit also afect kept jobs
    template:
      spec:
        # Provide your own container that you'd like to run as a Job Manager
        containers:
        - name: run-manager
          image: sailfish-run-manager
          imagePullPolicy: Always
          env:
            - name: MY_POD_NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
            - name: HOST
              value: sailfish-broker-hdls-svc.$(MY_POD_NAMESPACE).svc.cluster.local
            - name: QUEUE_PORT
              value: '5672'
          resources:
            requests:
              memory: "4G"
              cpu: '1'
            limits:
              memory: "4G"
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File          
        restartPolicy: Never
    backoffLimit: 4
    parallelism: 1   
  pollingInterval: 10 
  maxReplicaCount: 20             # Optional. Default: 100
  successfulJobsHistoryLimit: 1   # Optional. Default: 100. How many completed jobs should be kept.
  failedJobsHistoryLimit: 5       # Optional. Default: 100. How many failed jobs should be kept.
