apiVersion: keda.sh/v1alpha1
kind: ScaledJob
metadata:
  name: sailfish-worker-autoscaler
  labels:
    app: sailfish
    app.kubernetes.io/component: sailfish-worker
    app.kubernetes.io/instance: sailfish-worker
    app.kubernetes.io/name: sailfish-worker
    app.kubernetes.io/part-of: sailfish-worker
    app.openshift.io/runtime: python
spec:
  jobTargetRef:
    ttlSecondsAfterFinished: 100
    template:
      spec:
        # Make sure to select the node that belongs to your solution.
        nodeSelector:   
          sailfish/application: sailfish 
        tolerations:  
          - effect: NoSchedule
            key: application
            value: sailfish-hpc
        # Provide your own container that you'd like to run as a Job Manager
        containers:
        - name: task-worker
          image: sailfish-worker
          imagePullPolicy: Always
          env:
            - name: MY_POD_NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
            - name: HOST
              value: sailfish-broker-hdls-svc.$(MY_POD_NAMESPACE).svc.cluster.local
            - name: QUEUE_PORT
              value: '5672'
          resources:
            requests:
              memory: 2G
              cpu: 300m
            limits:
              memory: 2G
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File          
        restartPolicy: Never
    backoffLimit: 4
    parallelism: 1
  successfulJobsHistoryLimit: 1   # Optional. Default: 100. How many completed jobs should be kept.
  pollingInterval: 2 
  maxReplicaCount: 50             # Optional. Default: 100
  failedJobsHistoryLimit: 5       # Optional. Default: 100. How many failed jobs should be kept.
