apiVersion: keda.sh/v1alpha1
kind: TriggerAuthentication
metadata:
  name: sailfish-trigger-auth
spec:
  secretTargetRef:
  - parameter: bearerToken
    name: prometheus-token
    key: token
  - parameter: ca
    name: prometheus-token
    key: ca.crt