apiVersion: machine.openshift.io/v1beta1
kind: MachineSet
metadata:
  annotations:
    autoscaling.openshift.io/machineautoscaler: openshift-machine-api/ocp-7j9cc-sailfish-machineset-2-machineautoscaler
    machine.openshift.io/GPU: '0'
    machine.openshift.io/memoryMb: '65536'
    machine.openshift.io/vCPU: '16'
  name: ocp-7j9cc-sailfish-machineset-2
  namespace: openshift-machine-api
  labels:
    machines: sailfish
spec:
  replicas: 1
  selector:
    matchLabels:
      machine.openshift.io/cluster-api-cluster: ocp-7j9cc
      machine.openshift.io/cluster-api-machineset: ocp-7j9cc-sailfish-machineset-2
      ortec-finance/application: sailfish
  template:
    metadata:
      labels:
        machine.openshift.io/cluster-api-cluster: ocp-7j9cc
        machine.openshift.io/cluster-api-machine-role: worker
        machine.openshift.io/cluster-api-machine-type: worker
        machine.openshift.io/cluster-api-machineset: ocp-7j9cc-sailfish-machineset-2
        ortec-finance/application: sailfish
    spec:
      lifecycleHooks: {}
      metadata:
        labels:
          ortec-finance/application: sailfish
      providerSpec:
        value:
          osDisk:
            diskSettings: {}
            diskSizeGB: 128
            managedDisk:
              storageAccountType: Premium_LRS
            osType: Linux
          networkResourceGroup: rg-platform-001
          publicLoadBalancer: ocp-7j9cc
          userDataSecret:
            name: worker-user-data
          vnet: ocp-vnet
          credentialsSecret:
            name: azure-cloud-credentials
            namespace: openshift-machine-api
          zone: '2'
          metadata:
            creationTimestamp: null
          publicIP: false
          resourceGroup: rg-aro-prd-001
          kind: AzureMachineProviderSpec
          location: westeurope
          vmSize: Standard_D16as_v5
          image:
            offer: aro4
            publisher: azureopenshift
            resourceID: ''
            sku: aro_47
            version: 47.83.20210325
          subnet: worker-subnet
          apiVersion: azureproviderconfig.openshift.io/v1beta1
      taints:
        - effect: NoSchedule
          key: ortec-finance
          value: sailfish-application

