apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: sailfish-machines
spec:
  destination:
    namespace: 'openshift-machine-api'
    server: 'https://kubernetes.default.svc'
  project: sailfish
  ignoreDifferences:
  - group: machine.openshift.io
    kind: MachineSet
    jsonPointers:
    - /spec/replicas
  source:
    path: sailfish-k8s/cluster-config/machinesets
    repoURL: 'https://github.com/Ortec-Finance/sailfish-hpc.git'
    targetRevision: 'add-cluster-config'
    helm:
      parameters:
        - name: clusterName
          value: 'pearl-tst-s4pgx'
        - name: networkResourceGroup
          value: rg-pearl-001
        - name: clusterVnet
          value: pearl-tst-vnet
        - name: aroResourceGroup
          value: rg-aro-pearl-001
        - name: vmSize
          value: Standard_D4as_v5
  syncPolicy:
    automated:
      prune: true
      selfHeal: true