apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: sailfish-machines
spec:
  destination:
    namespace: 'openshift-machine-api'
    server: 'https://kubernetes.default.svc'
  project: default
  source:
    path: sailfish-k8s/cluster-config/machinesets
    repoURL: 'https://github.com/Ortec-Finance/sailfish-hpc.git'
    targetRevision: 'add-cluster-config'
    helm:
      parameters:
        - name: clusterName
          value: 'pearl-tst-s4pgx'
        - name: networkResourceGroup
          value: rg-platform-001
        - name: clusterVnet
          value: ocp-vnet
        - name: aroResourceGroup
          value: rg-aro-prd-001
        - name: vmSize
          value: Standard_D16as_v5
  syncPolicy:
    automated:
      prune: true
      selfHeal: true