resources:
 - ../foundation
 - permissions
 - servicemonitor.yaml
 - argo-cd-sync-ns-replacer.yaml

patches:
- target:
    group: keda.sh
    version: v1alpha1
    kind: ScaledJob
    name: sailfish-manager-autoscaler
  path: manager-trigger.yaml

- target:
    group: keda.sh
    version: v1alpha1
    kind: ScaledJob
    name: sailfish-worker-autoscaler
  path: worker-trigger.yaml