- op: replace
  path: "/spec/jobTargetRef/template/spec"
  value:
    nodeSelector:   
      ortec-finance/application: sailfish
    tolerations:  
      - effect: NoSchedule
        key: ortec-finance
        value: sailfish-application
    containers:
    - name: run-manager
      image: zeidaof/sailfish-runmanager
      imagePullPolicy: Always
      env:
        - name: AMQ_USER
          valueFrom:
            secretKeyRef:
              name: sailfish-broker-credentials-secret
              key: AMQ_USER
        - name: AMQ_PASSWORD
          valueFrom:
            secretKeyRef:
              name: sailfish-broker-credentials-secret
              key: AMQ_PASSWORD
        - name: HOST
          value: sailfish-broker-hdls-svc.sailfish.svc.cluster.local
        - name: QUEUE_PORT
          value: '5672'
      resources:
        requests:
          memory: "4000M"
          cpu: '1'
        limits:
          memory: "4000M"
      terminationMessagePath: /dev/termination-log
      terminationMessagePolicy: File          
    restartPolicy: Never