- op: replace
  path: "/spec/jobTargetRef/template/spec"
  value:
    containers:
    - name: consumer-job
      image: ofocp.azurecr.io/sailfish/rnmartingaletest:main
      imagePullPolicy: Always
      env:
        - name: TASK_ADDRESS
          value: sailfishWork
        - name: RESULT_ADDRESS
          value: sailfishResult
        - name: JOB_ADDRESS
          value: sailfishJob
        - name: USER
          valueFrom: 
            secretKeyRef:
              name: sailfish-broker-credentials-secret
              key: AMQ_USER
        - name: PASSWORD
          valueFrom:
            secretKeyRef:
              name: sailfish-broker-credentials-secret
              key: AMQ_PASSWORD
        - name: HOST
          value: sailfish-broker-hdls-svc.sav-rn-demo.svc.cluster.local
        - name: QUEUE_PORT
          value: '5672'
        - name: MODE
          value: 'JOB_MANAGER'
        - name: TIMEOUT
          value: '100'
        - name: DB_CONNECTION
          valueFrom: 
            secretKeyRef:
              name: sailfish-datastorage-secret
              key: CONNECTION_STRING
      resources: 
        requests:
          memory: "100M"
          cpu: "250m"
        limits:
          memory: "500M"
      terminationMessagePath: /dev/termination-log
      terminationMessagePolicy: File          
    restartPolicy: Never