- op: replace
  path: "/spec/jobTargetRef/template/spec"
  value:
    # Make sure to select the node that belongs to your solution.
    nodeSelector:   
      ortec-finance/application: sailfish
    tolerations:  
      - effect: NoSchedule
        key: ortec-finance
        value: sailfish-application
    # Provide your own container that you'd like to run as a Job Manager
    containers:
    - name: task-runner
      image: zeidaof/sailfish-runner
      imagePullPolicy: Always
      env:
        - name: AMQ_USER
          valueFrom:
            secretKeyRef:
              name: sailfish-broker-credentials-secret
              key: AMQ_USER
        - name: AMQ_PASSWORD
          valueFrom:
            secretKeyRef:
              name: sailfish-broker-credentials-secret
              key: AMQ_PASSWORD
        - name: HOST
          value: sailfish-broker-hdls-svc.rh-summit-demo.svc.cluster.local    # overwritten in overlay
        - name: QUEUE_PORT
          value: '5672'
      resources:
        requests:
          memory: 2G
          cpu: '1'
        limits:
          memory: 2G
      terminationMessagePath: /dev/termination-log
      terminationMessagePolicy: File          
    restartPolicy: Never