apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: sailfishclusters.ortec-finance.com
spec:
  group: ortec-finance.com
  versions:
    - name: v1alpha1
      served: true
      storage: true
      schema:
        openAPIV3Schema:
          type: object
          properties:
            spec:
              type: object
              required:
                - clusters
              properties:
                clusters:
                  required: 
                    - name
                  type: array
                  items:
                    type: object
                    properties:
                      name:
                        type: string
                      host:
                        type: string
                      queue:
                        type: string
                tolerations:
                  type: array
                  items:
                    type: object
                    required:
                      - name
                      - expr
                      - clusterRef
                    properties:
                      type:
                        type: string
                      name:
                        type: string
                      expr:
                        type: string
                      clusterRef:
                        type: string
                costFunction:
                  description: Optional Override cost function logic by injecting Python script
                  type: string
                triggers:
                  type: array
                  items:
                    required:
                      - name
                      - query
                      - clusterRef
                    type: object
                    description: Each variable is a metric that is used to calculate the best cluster to schedule the workload on. 
                    properties:
                      type:
                        type: string
                      name:
                        type: string
                      query:
                        type: string
                      scaler:
                        description: Scaler is combined with the query result to calculate the reward of this metric
                        type: number
                      clusterRef:
                        description: Which cluster does this variable represent?
                        type: string
            status:
              type: object
              properties:
                scheduler:
                  type: object
                  properties:
                    clusters:
                      type: array
                      items:
                        type: object
                        properties:
                          name:
                            type: string
                          result:
                            type: number
                            description: The result from the reward function by combining the query result and the scaler of every metric related to the cluster
                          toleration:
                            type: string
                            description: The toleration that is active on the cluster, if it is active no workloads will be scheduled onto it, even if it is the best option.
                          triggers:
                            type: array
                            description: The value of each trigger defined under variables
                            items:
                              type: object
                              properties:
                                name:
                                  type: string
                                value:
                                  type: number
                    operator:
                      type: string
                    activatedTargetCluster:
                      description: The current best destination based on the trigger variables and reward function
                      type: string
                clusters:
                  type: array
                  description: "Defines the Remote Sailfish Clusters"
                  items:
                    type: object
                    properties:
                      name:
                        type: string
                      queue:
                        type: string
                        description: "To reference a remote Sailfish Cluster, use this, the Queues will be automatically generated"
                      query:
                        type: string
                      status:
                        type: string
                      reason: 
                        type: string
                    required:
                      - name
  scope: Namespaced
  names:
    plural: sailfishclusters
    singular: sailfishcluster
    kind: SailfishCluster
    shortNames:
    - sc
  status:
    subresources:
      status: {}
