apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: sailfishclusters.ortec-finance.com
spec:
  group: ortec-finance.com
  versions:
    - name: v1alpha1
      served: true
      storage: true
      schema:
        openAPIV3Schema:
          type: object
          properties:
            status:
              type: object
              properties:
                clusters:
                  type: array
                  required:
                    - name
                    - status
                  items:
                    type: object
                    properties:
                      name:
                        type: string
                      status:
                        type: string
                      queue:
                        type: string
                      query:
                        type: string
                      reason:
                        type: string
            spec:
              type: object
              required:
                - cluster
              properties:
                triggers:
                  type: object
                  properties:
                    operator:
                      type: string
                    variables:
                      description: "List of queries that will be evaluated by the operator"
                      type: array
                      items:
                        type: object
                        properties:
                          type:
                            type: string
                          query:
                            type: string
                          clusterRef:
                            type: string
                            description: "Reference to the cluster that will be used if the value of the query is best compared to the other variables"
                        required:
                          - type
                          - query
                          - clusterRef
                cluster:
                  type: object
                  description: "Defines the Local Sailfish Cluster"
                  properties:
                    queue:
                      type: string
                clusters:
                  type: array
                  description: "Defines the Remote Sailfish Clusters"
                  items:
                    type: object
                    properties:
                      name:
                        type: string
                      host:
                        type: string
                        description: "To reference a remote Sailfish Cluster, use this, the Queues will be automatically generated"
                    required:
                      - name
  scope: Namespaced
  names:
    plural: sailfishclusters
    singular: sailfishcluster
    kind: SailfishCluster
    shortNames:
    - sc
  status:
    subresources:
      status: {}
