apiVersion: ortec-finance.com/v1alpha1
kind: SailfishCluster
metadata:
  name: sailfish-cluster
  namespace: rdlabs-experiment-cas-na-west
spec:
  clusters:      
    - name: eu  
      # Host is the acceptor of receiving broker    
      host: sailfish-broker-bridge-0-svc.rdlabs-experiment-cas-eu-west.svc.cluster.local
---
apiVersion: ortec-finance.com/v1alpha1
kind: SailfishCluster
metadata:
  name: sailfish-cluster
  namespace: rdlabs-experiment-cas-eu-west
spec:
  clusters:      
    - name: na      
      host: sailfish-broker-bridge-0-svc.rdlabs-experiment-cas-na-west.svc.cluster.local     