apiVersion: ortec-finance.com/v1alpha1
kind: SailfishCluster
metadata:
  name: sailfish-cluster
  namespace: rdlabs-experiment-cas-na-west
spec:
  clusters:
    - name: na ## This is the "local" cluster
      queue: sailfishJob      
    - name: eu
      host: sailfish-broker-bridge-0-svc.rdlabs-experiment-cas-eu-west.svc.cluster.local
  tolerations:
    - type: prometheus
      name: na_region_availability
      expr: azure_region_availability{region="westus"} > 10
      clusterRef: eu
    - type: prometheus
      name: eu_region_availability
      expr: azure_region_availability{region="westeurope"} > 10   
      clusterRef: eu
  costFunction: |
    # Optional Override reward function logic by injecting Python script
  triggers:
  - type: prometheus
    name: nl_carbon_intensity
    query: grid_intensity_carbon_average{location="NL"}
    scaler: 1 
    clusterRef: eu
  - type: prometheus
    name: us_carbon_intensity 
    query: grid_intensity_carbon_average{location="US-CAL-CISO"}
    scaler: 1
    clusterRef: na
---

apiVersion: ortec-finance.com/v1alpha1
kind: SailfishCluster
metadata:
  name: sailfish-cluster
  namespace: rdlabs-experiment-cas-eu-west
spec:
  clusters:
    - name: eu ## This is the "local" cluster
      queue: sailfishJob      
    - name: na
      host: sailfish-broker-bridge-0-svc.rdlabs-experiment-cas-na-west.svc.cluster.local
  tolerations:
    - type: prometheus
      name: na_region_availability
      expr: azure_region_availability{region="westus"} > 10
      clusterRef: eu
    - type: prometheus
      name: eu_region_availability
      expr: azure_region_availability{region="westeurope"} > 10   
      clusterRef: eu
  costFunction: |
    # Optional Override reward function logic by injecting Python script
  triggers:
  - type: prometheus
    name: nl_carbon_intensity
    query: grid_intensity_carbon_average{location="NL"}
    scaler: 1
    clusterRef: eu
  - type: prometheus
    name: us_carbon_intensity 
    query: grid_intensity_carbon_average{location="US-CAL-CISO"}
    scaler: 1
    clusterRef: na