resources:
 - ../foundation
 - trigger-authentication.yaml
 - servicemonitor.yaml
 - rb.yaml
 - sa.yaml
 - prometheus-token.yaml

patches:
- target:
    group: keda.sh
    version: v1alpha1
    kind: ScaledJob
    name: sailfish-run-manager-autoscaler
  path: run-manager-trigger.yaml

- target:
    group: keda.sh
    version: v1alpha1
    kind: ScaledJob
    name: sailfish-runner-autoscaler
  path: runner-trigger.yaml