apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: sailfish-prometheus-view
subjects:
- kind: ServiceAccount
  name: sailfish
roleRef:
  kind: ClusterRole
  name: cluster-monitoring-view
  apiGroup: rbac.authorization.k8s.io
