apiVersion: v1
kind: Service
metadata:
  name: cluster-availability-exporter
  labels:
    app.kubernetes.io/name: cluster-availability-exporter
  annotations:
    prometheus.io/scrape: "true"
spec:
  type: ClusterIP
  clusterIP: None
  ports:
    - port: 8000
      protocol: TCP
      name: http
    - port: 5000
      protocol: TCP
      name: metrics
  selector:
    app.kubernetes.io/name: cluster-availability-exporter