{
 "title": "Sailfish",
 "time": { "from": "now-30m", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   {
    "name": "machine_set_zone_1",
    "label": "Machine Set 1",
    "query": {
     "query": "label_values(mapi_machine_set_status_replicas, name)"
    }
   },
   {
    "name": "machine_set_zone_2",
    "label": "Machine Set 2",
    "query": {
     "query": "label_values(mapi_machine_set_status_replicas, name)"
    }
   },
   {
    "name": "machine_set_zone_3",
    "label": "Machine Set 3",
    "query": {
     "query": "label_values(mapi_machine_set_status_replicas, name)"
    }
   },
   { "name": "namespace", "label": "Namespace", "query": { "query": "label_values(namespace)" } }
  ]
 },
 "panels": [
  {
   "type": "text",
   "gridPos": { "h": 3, "w": 24, "x": 0, "y": 0 },
   "options": {
    "content": "<h1 style=\"font-size: 62px;text-align:center;\">Sailfish Monitoring<h1>\r\n"
   }
  },
  {
   "type": "text",
   "gridPos": { "h": 2, "w": 8, "x": 0, "y": 3 },
   "options": {
    "content": "<h3 style=\"text-align:center; font-size: 24px;\"> Zone 1 </h3>"
   }
  },
  {
   "type": "text",
   "gridPos": { "h": 2, "w": 8, "x": 8, "y": 3 },
   "options": {
    "content": "<h3 style=\"text-align:center; font-size: 24px;\"> Zone 2 </h3>"
   }
  },
  {
   "type": "text",
   "gridPos": { "h": 2, "w": 8, "x": 16, "y": 3 },
   "options": {
    "content": "<h3 style=\"text-align:center; font-size: 24px;\"> Zone 3 </h3>"
   }
  },
  {
   "title": "Zone Capacity",
   "type": "graph",
   "gridPos": { "h": 9, "w": 8, "x": 0, "y": 5 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(kube_node_status_capacity{cluster=\"\", node=~\"${machine_set_zone_1}.+\", resource=\"cpu\"})\r",
     "legendFormat": "CPU Capacity"
    },
    {
     "expr": "sum(rate(container_cpu_usage_seconds_total{cluster=\"\",node=~\"${machine_set_zone_1}.+\", namespace=\"${namespace}\"}[1m]))\r",
     "legendFormat": "CPU Usage"
    }
   ]
  },
  {
   "title": "Zone Capacity",
   "type": "graph",
   "gridPos": { "h": 9, "w": 8, "x": 8, "y": 5 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(kube_node_status_capacity{cluster=\"\", node=~\"${machine_set_zone_2}.+\", resource=\"cpu\"})\r",
     "legendFormat": "CPU Capacity"
    },
    {
     "expr": "sum(rate(container_cpu_usage_seconds_total{cluster=\"\",node=~\"${machine_set_zone_2}.+\", namespace=\"${namespace}\"}[1m]))\r",
     "legendFormat": "CPU Usage"
    }
   ]
  },
  {
   "title": "Zone Capacity",
   "type": "graph",
   "gridPos": { "h": 9, "w": 8, "x": 16, "y": 5 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(kube_node_status_capacity{cluster=\"\", node=~\"${machine_set_zone_3}.+\", resource=\"cpu\"})\r",
     "legendFormat": "CPU Capacity"
    },
    {
     "expr": "sum(rate(container_cpu_usage_seconds_total{cluster=\"\",node=~\"${machine_set_zone_3}.+\", namespace=\"${namespace}\"}[1m]))\r",
     "legendFormat": "CPU Usage"
    }
   ]
  },
  {
   "title": "Tasks",
   "type": "stat",
   "gridPos": { "h": 8, "w": 2, "x": 0, "y": 14 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "sum(artemis_message_count{namespace=\"${namespace}\",address=\"sailfishJob\",broker=\"amq-broker\",queue=\"sailfishJob\",})+sum(artemis_message_count{namespace=\"${namespace}\",address=\"sailfishResult\",broker=\"amq-broker\",queue=\"sailfishResult\",}) + sum(artemis_message_count{namespace=\"${namespace}\",address=\"sailfishTask\",broker=\"amq-broker\",queue=\"sailfishTask\",})",
     "legendFormat": "Tasks"
    }
   ]
  },
  {
   "title": "Workers",
   "type": "stat",
   "gridPos": { "h": 8, "w": 2, "x": 2, "y": 14 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(kube_job_info{namespace=\"${namespace}\", job_name=~\"sailfish-worker.+\"})",
     "legendFormat": "Workers"
    }
   ]
  },
  {
   "title": "Desired Node Count",
   "type": "stat",
   "gridPos": { "h": 8, "w": 3, "x": 4, "y": 14 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(mapi_machine_set_status_replicas{name=\"${machine_set_zone_1}\"})+sum(mapi_machine_set_status_replicas{name=\"${machine_set_zone_2}\"})+sum(mapi_machine_set_status_replicas{name=\"${machine_set_zone_3}\"}) ",
     "legendFormat": "Nodes"
    }
   ]
  },
  {
   "title": "TOTAL MEMORY Usage",
   "type": "stat",
   "gridPos": { "h": 8, "w": 5, "x": 7, "y": 14 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "avg((avg(container_memory_working_set_bytes{namespace=\"${namespace}\"}) by (container_name , pod ))/ on (container_name , pod)(avg (container_spec_memory_limit_bytes>0 ) by (container_name, pod)))",
     "legendFormat": "GB"
    }
   ]
  },
  {
   "title": "TOTAL CPU Usage",
   "type": "stat",
   "gridPos": { "h": 8, "w": 5, "x": 12, "y": 14 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(rate(container_cpu_usage_seconds_total{namespace=\"${namespace}\"}[1m]))",
     "legendFormat": "CPU"
    }
   ]
  },
  {
   "title": "Available CPU Power",
   "type": "stat",
   "gridPos": { "h": 8, "w": 7, "x": 17, "y": 14 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(kube_node_status_capacity{cluster=\"\", node=~\"${machine_set_zone_1}.+\", resource=\"cpu\"})+sum(kube_node_status_capacity{cluster=\"\", node=~\"${machine_set_zone_2}.+\", resource=\"cpu\"})+sum(kube_node_status_capacity{cluster=\"\", node=~\"${machine_set_zone_3}.+\", resource=\"cpu\"})\r\r",
     "legendFormat": "CPU"
    }
   ]
  },
  {
   "title": "CPU Utilization",
   "type": "graph",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 22 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(container_cpu_usage_seconds_total{namespace=\"${namespace}\",}[1m]) > 0.1",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "Memory Utilization",
   "type": "graph",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 30 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "(avg(container_memory_working_set_bytes{namespace=\"${namespace}\"}) by (container_name , pod ))/ on (container_name , pod)(avg (container_spec_memory_limit_bytes>0 ) by (container_name, pod))",
     "legendFormat": "{{pod}}"
    }
   ]
  }
 ]
}