apiVersion: v1
kind: Namespace
metadata:
  name: openshift-serverless
  annotations:
    argocd.argoproj.io/sync-wave: "0"
spec: {}
---
apiVersion: v1
kind: Namespace
metadata:
  name: knative-serving
  annotations:
    argocd.argoproj.io/sync-wave: "0"
spec: {}

