apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: sailfish-operators
spec:
  destination:
    server: 'https://kubernetes.default.svc'
  project: sailfish
  source:
    path: k8s/cluster-config/operators
    repoURL: 'https://github.com/Ortec-Finance/sailfish-hpc.git'
    targetRevision: 'main'
  syncPolicy:
    automated:
      prune: true
      selfHeal: true