apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: sailfish
spec:
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: sailfish-demo
  project: sailfish
  ## This is needed for the broker to be able to scale to zero!
  ignoreDifferences:
    - group: broker.amq.io
      kind: ActiveMQArtemis
      jsonPointers:
      - /spec/deploymentPlan/size
  ## There is a Post Sync job that automates the replacement of the namespace in the triggers
    - group: keda.sh
      kind: ScaledJob
      jsonPointers:
      - /spec/triggers/0/metadata/namespace
      - /spec/triggers/1/metadata/namespace
      - /spec/triggers/2/metadata/namespace
      - /spec/triggers/3/metadata/namespace
      - /spec/triggers/4/metadata/namespace
      - /spec/triggers/5/metadata/namespace
    - group: keda.sh
      kind: ScaledObject
      jsonPointers:
      - /spec/triggers/0/metadata/namespace
      - /spec/triggers/1/metadata/namespace
      - /spec/triggers/2/metadata/namespace
      - /spec/triggers/3/metadata/namespace
      - /spec/triggers/4/metadata/namespace
      - /spec/triggers/5/metadata/namespace
  source:
    path: k8s/sailfish/overlays/demo
    repoURL: 'https://github.com/Ortec-Finance/sailfish-hpc.git'
    targetRevision: 'main'
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
    retry:
      limit: 20
      backoff:
        duration: 60s
        factor: 1
        maxDuration: 2m